# Generated by Django 5.2 on 2025-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertisearea',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userexpertise',
            name='verification_method',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_method_expertise',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
