# Generated by Django 5.2 on 2025-05-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectattachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='file_size',
            field=models.PositiveIntegerField(help_text='Size in octets'),
        ),
    ]
