# Generated by Django 5.2 on 2025-04-16 21:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount, usually the project budget', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('held', 'Held in Escrow'), ('released', 'Released to Collaborator'), ('refunded', 'Refunded to Client'), ('failed', 'Payment Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id_provider', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('project', models.OneToOneField(help_text='Associated project for this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
