# Generated by Django 5.2 on 2025-04-16 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('project_created', 'Project Created'), ('application_received', 'New Application Received'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('project_assigned', 'Project Assigned to You'), ('project_status_update', 'Project Status Updated'), ('project_completed', 'Project Completed'), ('project_revision_requested', 'Project Revision Requested'), ('new_message', 'New Chat Message'), ('payment_held', 'Payment Held in Escrow'), ('payment_released', 'Payment Released'), ('payment_failed', 'Payment Failed')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='The notification message content.')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(blank=True, max_length=36, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx')],
            },
        ),
    ]
