# Generated by Django 5.2 on 2025-06-01 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de lecture de la notification', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text="Type de contenu de l'objet associé", null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de création de la notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique de la notification', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indique si la notification a été lue'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, help_text='Contenu du message de notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_created', 'Projet créé'), ('application_received', 'Nouvelle candidature reçue'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature rejetée'), ('project_assigned', 'Projet assigné'), ('project_status_update', 'Statut du projet mis à jour'), ('project_completed', 'Projet terminé'), ('project_revision_requested', 'Révision du projet demandée'), ('new_message', 'Nouveau message de chat'), ('payment_held', 'Paiement bloqué en dépôt de garantie'), ('payment_released', 'Paiement libéré'), ('payment_failed', 'Échec du paiement')], help_text='Type de notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, help_text="Identifiant de l'objet associé", max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='Utilisateur destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
    ]
